export const WSOL = "So11111111111111111111111111111111111111112";
export const RENT_TIMES_ARRAY = [
  {
    label: "15 minutes",
    timeSeconds: 900,
    priceSolana: 0.005,
  },
  {
    label: "1 hour",
    timeSeconds: 3600,
    priceSolana: 0.01,
  },
  {
    label: "2 hour",
    timeSeconds: 3600 * 2,
    priceSolana: 0.02,
  },
  {
    label: "3 hour",
    timeSeconds: 3600 * 3,
    priceSolana: 0.03,
  },
];
export const icons = {
  green: "🟢",
  red: "🔴",
  white: "⚪️",
  black: "⚫️",
  globe: "🌐",
  rocket: "🚀",
  lock: "🔐",
  lightning: "⚡️",
  hourglassFull: "⏳",
  hourglassEmpty: "⌛️",
  clockRed: "⏰",
  clockAntique: "🕰",
  diskette: "💾",
  tool: "🛠",
  key: "🔑",
  keyAntique: "🗝",
  moonPlanet: "🪐",
  moonYellow: "🌕",
  moonWhite: "🪙",
  chainLink: "🔗",
  chartUpRed: "📈",
  chartBars: "📊",
  volumeBoosters: "📊",
  holderBoosters: "💼",
  rankBoosters: "🏆",
  alienHappy: "👾",
  flame: "🔥",
  tractor: "🚜",
  truck: "🚛",
  car: "🚙",
  copcar: "🚓",
  racecar: "🏎",
  shield: "🛡️",
  plane: "✈️",
  questionRed: "❓",
  questionWhite: "❔",
  cup: "🏆",
  goblet: "🏆",
  people: "👫",
  peopleGrayFaceless: "🫂",
  lifebuoy: "🛟",
  ape: "🦧",
  bot: "🤖",
  bag: "🎒",
  attention: "⚠️",
  warning: "⚠️",
  robot:"🤖",
  upmarket: "📈",
  downmarket: "📉",
  greenSquare: "🟩",
  check: "✅",
  cross: "❌",
  backArrow: "↪️",
  rightArrow: "➡️",
  leftArrow: "⬅️",
  diagonalUpArrow: "↗️",
  diagonalDownArrow: "↘️",
  chevronLeft: "◀️",
  chevronRight: "▶️",
  circularArrow: "🔄",
  refresh: "🔄",
  arrowDoubledown: "⏬️",
  write: "📝",
  read: "📖",
  sprout: "🌱",
  lighting: "⚡",
  book: "📖",
  plus: "➕",
  minus: "➖",
  cashBanknote: "💵",
  cashBag: "💰",
  cashBankHouse: "🏦",
  cashDiamond: "💎",
  cashFaceTongue: "🤑",
  strongArm: "💪",
  anger: "🤬",
  salute: "🫡",
  thumbUp: "👍",
  thumbDown: "👎",
  handshake: "🤝",
  fingersCrossed: "🫰",
};